import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  experimental: {
    externalTables: true, // Required for this feature as of 2026
  },
  tables: {
    external: [
      'public.admin_user_takeover',
      'public.agency',
      'public.agent_setup',
      'public.ai_suggestions',
      'public.billing_customer',
      'public.billing_plan',
      'public.billing_plan_features',
      'public.billing_subscription',
      'public.chat_message',
      'public.city_map',
      'public.collaborator',
      'public.daily_outreach',
      'public.daily_outreach_cities',
      'public.daily_outreach_follow_up_msgs',
      'public.daily_outreach_profiles',
      'public.daily_outreach_templates',
      'public.dispatcher_analytics',
      'public.dm_messages',
      'public.dm_quota',
      'public.dm_req',
      'public.dm_threads',
      'public.event_answer',
      'public.event_batches',
      'public.event_guest',
      'public.event_invitations',
      'public.event_js',
      'public.event_question',
      'public.event_share',
      'public.events',
      'public.events_club_ethnicities',
      'public.events_club_filter_ids',
      'public.events_club_hair_colors',
      'public.events_club_profile_types',
      'public.events_dinner_ethnicities',
      'public.events_dinner_filter_ids',
      'public.events_dinner_hair_colors',
      'public.events_dinner_profile_types',
      'public.events_pre_drink_ethnicities',
      'public.events_pre_drink_filter_ids',
      'public.events_pre_drink_hair_colors',
      'public.events_pre_drink_profile_types',
      'public.follow_up_msg',
      'public.following',
      'public.ghost_protocol_tracking',
      'public.ig_session',
      'public.message',
      'public.msg_check',
      'public.msg_history',
      'public.msg_profile',
      'public.my_filter',
      'public.new_face',
      'public.notification',
      'public.outreach_log',
      'public.picture',
      'public.polling_state',
      'public.promoter_agent_conversation',
      'public.proxy',
      'public.recognition',
      'public.spring_session',
      'public.spring_session_attributes',
      'public.story_hist',
      'public.talent_pool',
      'public.thread',
      'public.thread_admin_takeover',
      'public.tp_status',
      'public.tracker',
      'public.translation_cache',
      'public.trust_score_history',
      'public.user_tp_status',
      'public.user_tracker',
      'public.users',
      'public.zone_map',
    ],
  },
});
