-- AlterTable
ALTER TABLE "Campaign" ALTER COLUMN "eventId" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "CampaignInvitation" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "eventId" SET DATA TYPE BIGINT;
